### ISSUE TITLE
Add the option to use a pa11y.json

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/ddev-pa11y#1]
Pally allows the use of a configuration file https://github.com/pa11y/pa11y?tab=readme-ov-file#command-line-configuration
Allows users to override this configuration creating the file.

Currently, the command gets the default config.json
```
/app/node_modules/.bin/pa11y -c /app/config/config.json "$@"
```

**Comment by juanjol** [comment]
This is now fixed, config file can be edited. Thank you @Eduardo-Morales-Alberti !
